### ISSUE TITLE
Réparation chaise de terrasse pour Colette (landlordess)

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/devis-et-facturation#1]
### Message :

"Est-ce qu'il y a moyen de la réparer? Je payerai le tps que ça prend. bisous"

#### Contexte :
Une chaise a cassé sur son axe. 

![image](https://user-images.githubusercontent.com/12049360/44395692-f1e80100-a53a-11e8-931c-dd361d7ad663.png)

La vis est simplement comme ça
![image](https://user-images.githubusercontent.com/12049360/44395750-21970900-a53b-11e8-8821-5520cd273641.png)

#### Objectif :

Réparer suffisament la chaise pour qu'elle ne soit pas à jeter. 

#### Process :

Proposition est de 
- reboucher à la pâte à bois (cosmetics)
- reforer un peu plus loin dans le bois pas abimé
- faire pareil de l'autre côté pas cassé
- rendre un peu ça joli, poncer, nettoyer. 

---

#### Deadline

asap, winter is coming....

#### To do : 
- [x] Publier dans la team job github et sur le channel slack
- [x] Répondre au client qu'on traite sa demande
- [ ] Assigner quelqu'un
- [ ] Rédiger devis
- [ ] Faire relire devis
- [ ] Envoyer devis
- [ ] Fabrication
- [ ] Facturation

#### Team : 

- Back office : _@user_
- Design : _@user_
- Production : _@user_

**Comment by zuperninja** [comment]
https://github.com/orgs/openfab-lab/teams/team-job/discussions/10

Les jobs se mettent dans la team Job en discussion. 
Les issues se sont pour les problèmes sur la méthodologie des devis et facture

Signé : Germaine
